"""Research outcomes and backtest runs.

Purely additive: three new tables and their indexes. No existing table is
touched, so the clean candle provenance established by the phase 4.2 baseline is
carried forward untouched -- a migration that rewrote market data to add a
research feature would destroy the very thing the research is measured against.

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-11 23:03:08.971203

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.db.types

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_key", sa.String(length=64), nullable=False),
        sa.Column("started_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("completed_at", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("from_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("to_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "universe_definition",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("primary_timeframe", sa.String(length=8), nullable=False),
        sa.Column("regular_session_only", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column("signal_model_version", sa.String(length=32), nullable=False),
        sa.Column("scanner_policy_version", sa.String(length=32), nullable=False),
        sa.Column("cost_model_version", sa.String(length=32), nullable=False),
        sa.Column("label_policy_version", sa.String(length=32), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="RUNNING", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("observation_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("symbols_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.create_index("ix_backtest_runs_run_key", ["run_key"], unique=False)
        batch_op.create_index("ix_backtest_runs_started_at", ["started_at"], unique=False)
        batch_op.create_index("ix_backtest_runs_status", ["status"], unique=False)

    op.create_table(
        "signal_outcomes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("horizon", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.Integer(), server_default="1", nullable=False),
        sa.Column("reference_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.Column("reference_price", app.db.types.Money(precision=18, scale=6), nullable=False),
        sa.Column("future_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("future_price", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("raw_return", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("target_status", sa.String(length=24), nullable=True),
        sa.Column("stop_status", sa.String(length=24), nullable=True),
        sa.Column("barrier_outcome", sa.String(length=24), nullable=True),
        sa.Column("time_to_target_seconds", sa.Float(), nullable=True),
        sa.Column("time_to_stop_seconds", sa.Float(), nullable=True),
        sa.Column(
            "ambiguous_bar_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("label_timeframe", sa.String(length=8), nullable=True),
        sa.Column("bars_observed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rolled_to_next_session", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("label_policy_version", sa.String(length=32), nullable=False),
        sa.Column("computed_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["signal_evaluations.id"],
            name=op.f("fk_signal_outcomes_evaluation_id_signal_evaluations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_outcomes")),
        sa.UniqueConstraint(
            "evaluation_id",
            "horizon",
            "direction",
            "label_policy_version",
            name="uq_signal_outcome_evaluation_horizon",
        ),
    )
    with op.batch_alter_table("signal_outcomes", schema=None) as batch_op:
        batch_op.create_index("ix_signal_outcomes_evaluation", ["evaluation_id"], unique=False)
        batch_op.create_index("ix_signal_outcomes_horizon", ["horizon"], unique=False)
        batch_op.create_index("ix_signal_outcomes_status", ["status"], unique=False)

    op.create_table(
        "trade_outcomes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("backtest_run_id", sa.Integer(), nullable=True),
        sa.Column("simulation_profile_id", sa.Integer(), nullable=False),
        sa.Column("profile_key", sa.String(length=32), nullable=False),
        sa.Column("executed", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("rejection_reason", sa.String(length=48), nullable=True),
        sa.Column("entry_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("entry_price", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("exit_timestamp", app.db.types.UTCDateTime(timezone=True), nullable=True),
        sa.Column("exit_price", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("quantity", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("exit_reason", sa.String(length=32), nullable=True),
        sa.Column("gross_pnl", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("fees", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("spread_cost", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("slippage_cost", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("net_pnl", app.db.types.Money(precision=18, scale=6), nullable=True),
        sa.Column("net_return", sa.Float(), nullable=True),
        sa.Column("holding_period_seconds", sa.Float(), nullable=True),
        sa.Column("modelled_spread_bps", sa.Float(), nullable=True),
        sa.Column("cost_basis", sa.String(length=16), nullable=False),
        sa.Column("spread_quality", sa.String(length=24), nullable=True),
        sa.Column("session_phase", sa.String(length=16), nullable=True),
        sa.Column("cost_model_version", sa.String(length=32), nullable=False),
        sa.Column("label_policy_version", sa.String(length=32), nullable=False),
        sa.Column("computed_at", app.db.types.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"],
            ["backtest_runs.id"],
            name=op.f("fk_trade_outcomes_backtest_run_id_backtest_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["signal_evaluations.id"],
            name=op.f("fk_trade_outcomes_evaluation_id_signal_evaluations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_profile_id"],
            ["simulation_profiles.id"],
            name=op.f("fk_trade_outcomes_simulation_profile_id_simulation_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_outcomes")),
        sa.UniqueConstraint(
            "evaluation_id",
            "simulation_profile_id",
            "backtest_run_id",
            "cost_model_version",
            name="uq_trade_outcome_evaluation_profile",
        ),
    )
    with op.batch_alter_table("trade_outcomes", schema=None) as batch_op:
        batch_op.create_index("ix_trade_outcomes_evaluation", ["evaluation_id"], unique=False)
        batch_op.create_index("ix_trade_outcomes_profile", ["profile_key"], unique=False)
        batch_op.create_index("ix_trade_outcomes_run", ["backtest_run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_outcomes", schema=None) as batch_op:
        batch_op.drop_index("ix_trade_outcomes_run")
        batch_op.drop_index("ix_trade_outcomes_profile")
        batch_op.drop_index("ix_trade_outcomes_evaluation")

    op.drop_table("trade_outcomes")
    with op.batch_alter_table("signal_outcomes", schema=None) as batch_op:
        batch_op.drop_index("ix_signal_outcomes_status")
        batch_op.drop_index("ix_signal_outcomes_horizon")
        batch_op.drop_index("ix_signal_outcomes_evaluation")

    op.drop_table("signal_outcomes")
    with op.batch_alter_table("backtest_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_backtest_runs_status")
        batch_op.drop_index("ix_backtest_runs_started_at")
        batch_op.drop_index("ix_backtest_runs_run_key")

    op.drop_table("backtest_runs")
    # ### end Alembic commands ###
