"""Backtest isolation marker on signal_evaluations.

One nullable column. NULL means the live scanner wrote the row; a value means a
historical replay did. Every production read filters on NULL, which is what lets
research and production share one observation schema without a backtest ever
appearing in the live candidate list while the scheduler is running.

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-11 23:09:06.327260

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backtest_run_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_signal_evaluations_backtest_run"), ["backtest_run_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_signal_evaluations_backtest_run_id_backtest_runs"),
            "backtest_runs",
            ["backtest_run_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("signal_evaluations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_signal_evaluations_backtest_run_id_backtest_runs"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_signal_evaluations_backtest_run"))
        batch_op.drop_column("backtest_run_id")

    # ### end Alembic commands ###
